import { useEffect, useState } from 'react';
import Navbar from '../../components/Navbar';
import Sidebar from '../../components/Sidebar';
import Button from '../../components/Button';
import Loading from '../../components/Loading';
import { createHoliday, deleteHoliday, getHolidays, updateHoliday } from '../../services/holidayService';

const blank = { name: '', date: '', description: '' };
function Holidays() { const [items, setItems] = useState(null); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const load = () => getHolidays().then(setItems).catch(() => setError('Unable to load holidays.')); useEffect(() => { load(); }, []); const submit = async (event) => { event.preventDefault(); try { if (editing) await updateHoliday(editing, form); else await createHoliday(form); setForm(blank); setEditing(null); await load(); } catch { setError('Unable to save holiday.'); } }; const remove = async (id) => { try { await deleteHoliday(id); setItems((current) => current.filter((item) => item.id !== id)); } catch { setError('Unable to delete holiday.'); } }; if (!items) return <Frame><Loading message="Loading holidays..." /></Frame>; return <Frame><section className="panel"><div className="panel-header"><h3>{editing ? 'Edit holiday' : 'Add holiday'}</h3></div><form onSubmit={submit}><div className="leave-form-grid"><Field label="Name" name="name" value={form.name} setForm={setForm} /><Field label="Date" name="date" type="date" value={form.date} setForm={setForm} /><div className="field-group full-span"><label>Description</label><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div></div><div className="leave-actions"><Button type="submit">{editing ? 'Update' : 'Add holiday'}</Button>{editing && <Button variant="secondary" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</Button>}</div></form></section>{error && <div className="empty-state error-state">{error}</div>}<section className="panel"><div className="panel-header"><h3>Holiday calendar</h3></div>{items.length === 0 ? <div className="empty-state">No holidays added.</div> : <div className="leave-history-list">{items.map((item) => <div className="leave-history-row" key={item.id}><div><strong>{item.name}</strong><small>{item.date}</small><small>{item.description || 'Company holiday'}</small></div><div className="inline-actions"><Button variant="secondary" onClick={() => { setEditing(item.id); setForm({ name: item.name || '', date: item.date || '', description: item.description || '' }); }}>Edit</Button><Button variant="secondary" onClick={() => remove(item.id)}>Delete</Button></div></div>)}</div>}</section></Frame>; }
function Field({ label, name, type = 'text', value, setForm }) { return <div className="field-group"><label>{label}</label><input required name={name} type={type} value={value} onChange={(event) => setForm((current) => ({ ...current, [name]: event.target.value }))} /></div>; }
function Frame({ children }) { return <div className="dashboard-shell"><Sidebar /><main className="main-panel"><Navbar title="Holidays" />{children}</main></div>; }
export default Holidays;
